# Generated by Django 3.1.6 on 2021-02-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(null=True),
        ),
    ]
